solver:
  n_seed: 7

  # initial condition
  I0: 0.1
  R0: 0.0
  # S0 = 1 - I0 - R0 (computed in Python)
  T: 40.0
  Nstates: 3

  batch_size: 100
  valid_size: 200
  n_maxstep: 10000 #
    
  n_displaystep: 5
  n_savetofilestep: 10
  stdNN: 0.01

  lr_boundaries: [100]
  lr_values: [0.01, 0.01]


  # epidemiological parameters (passed to FBODE)
  beta: [0.4, 0.4, 0.3]           
  gamma: 0.1
  lambda1: 1.0
  lambda2: 0.9
  lambda3: 1.0
  alpha_I_pop: 0.9                 # = lambda2
  cost_I: 1.0
  cost_lambda1: 10.0
  kappa: 0.0 #reinfection

  g: 0.2
  Delta_t: 0.05

graphon:
  graphon_mode: piecewise #constant/powerlaw/star/piecewise

  constant:
    p: 0.3

  powerlaw: 
    g: 0.2

  star:
    hub_threshold: 0.05

  piecewise:
    group_bounds: [0.0, 0.4, 0.6, 1.0]
    Wblocks:
      - [1.0, 0.5, 0.3]
      - [0.5, 1.0, 0.4]
      - [0.3, 0.4, 1.0]
